// <auto-generated />
using Library_Management_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Library_Management_System.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Library_Management_System.Models.BookModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CopiesAvailable")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimesBorrowed")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Miguel de Cervantes",
                            CopiesAvailable = 4,
                            ISBN = "9780060934347",
                            TimesBorrowed = 6,
                            Title = "Don Quixote"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Lewis Carroll",
                            CopiesAvailable = 3,
                            ISBN = "9781503250212",
                            TimesBorrowed = 5,
                            Title = "Alice's Adventures in Wonderland"
                        },
                        new
                        {
                            Id = 3,
                            Author = "J.R.R. Tolkien",
                            CopiesAvailable = 5,
                            ISBN = "9780261102385",
                            TimesBorrowed = 12,
                            Title = "The Lord of The Rings"
                        },
                        new
                        {
                            Id = 4,
                            Author = "J.R.R. Tolkien",
                            CopiesAvailable = 2,
                            ISBN = "9780261102217",
                            TimesBorrowed = 9,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Alexandre Dumas",
                            CopiesAvailable = 6,
                            ISBN = "9780140449266",
                            TimesBorrowed = 8,
                            Title = "The Count of Monte Cristo"
                        });
                });

            modelBuilder.Entity("Library_Management_System.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
